### ISSUE TITLE
Support for NeoEE .exe binaries

### ISSUE THREAD

**Issue by giaur89** [j-frei/EmpireEarthZoomChanger#1]
NeoEE is a great community of EE players, it offers also NeoEE patch that makes EE better customized for modern computers and allows to play EE online. Link: https://www.neoee.net/

Sadly, this great and needed EEZoomChanger doesn't support NeoEE patched .exe binaries.

Please if someone could add support for these binaries. Thanks! Attached NeoEE .exe binaries.

[NeoEE.zip](https://github.com/j-frei/EmpireEarthZoomChanger/files/4677209/NeoEE.zip)

**Comment by j-frei** [comment]
Thank you for providing the files. I will have a look at it eventually.

**Comment by j-frei** [comment]
@giaur89 I have updated the binary at the release page. The files should be supported now. Can you give it a try?
https://github.com/j-frei/EmpireEarthZoomChanger/releases

**Comment by giaur89** [comment]
@j-frei thank you very much for having a look on it. I gave it a try on NeoEE binaries but it won't work - I have information popping up that "EmpireEarthZoomChanger.exe stopped working". I tried also on original binaries and with them everything is alright - "File was successfully patched" information is popping up.

Thank you for your precious work.

**Comment by j-frei** [comment]
@giaur89 
Indeed.
I forgot to change another piece of code that is responsible for determining the write location and just tested the loading part. :facepalm: 

The release file as well as the code are fixed. Could you please try again and report?

**Comment by giaur89** [comment]
@j-frei Now it works perfectly fine! Checked on Windows 7 x64 and Windows 10 x64.

Once again thank you for your good work :))
