### ISSUE TITLE
False Positive Warning on Win10

### ISSUE THREAD

**Issue by Linkinsoldier** [j-frei/EmpireEarthZoomChanger#2]
When trying to open the .exe to patch my EE Installation, I get the following false positive:

![False Positiv - trotzdem ausführbar](https://user-images.githubusercontent.com/24806068/86510937-a3714200-bdf4-11ea-8595-ec0987882687.png)

Can this be fixed?

**Comment by HerMajestyDrMona** [comment]
Hi Linkinsoldier.
SmartScreen alerts are normal. It means that the program is "unknown", "unrecognized", "not popular" (has not many active users).
I've wrote a little longer explanation here: https://forum.ee2.eu/viewtopic.php?p=25628#p25628 when a similar problem was reported in unofficial patch for EE2 topic.

> Can this be fixed?
You're supposed to click "More information" (Weitere informationen) hyperlink. Then a "Run anway" button will appear.

**Comment by Linkinsoldier** [comment]
Sorry, I should have been more precise: going around it was not the problem - i was just pointing out the false positive, so it might get fixed. Same goes for the virus total false positive:
https://www.virustotal.com/gui/file/e3ff445283018fbcfdd9b0c903443cf1e3559a2092d115617373f4d4c2c4a6ef/detection

**Comment by HerMajestyDrMona** [comment]
Still, the compiled executable has a low popularity. Therefore SmartScreen alerts users that it might be potentially dangerous. It happens to all new programs downloaded from the Internet.
False Positives on VirusTotal: "SecureAge APEX" and "VBA32"... First time hearing those names. Why should it even matter?

If you really want to get it "fixed", then:
https://www.secureaplus.com/features/antivirus/report-false-positive/
https://twitter.com/seeingwithsound/status/300633422286708736

Please remember that "EmpireEarthZoomChanger" modifies the game process memory at certain addresses. It's kind of "hacking", so sooner or later more AV programs might find it suspicious. This really should not be an issue, especially for an open source software like this. Everyone interested can view the source code and compile themselves.

**Comment by Linkinsoldier** [comment]
Thank you - i did report it. Hope it will get fixed from the AV developers.

**Comment by Linkinsoldier** [comment]
VBA32 wrote back, that the false positive will be removed with the next release.
