### ISSUE TITLE
Zoom Editor doesnt work for Szenario Editor

### ISSUE THREAD

**Issue by Linkinsoldier** [j-frei/EmpireEarthZoomChanger#3]
This tool works great in the game - however it does not work in the szenario editor (which therefore looks really bad!). Is there any chance to make this work in the szenario editor as well?

Thank you,
Linkin

**Comment by j-frei** [comment]
Hi @Linkinsoldier 

thank you for your message! Sorry for my late answer. Somehow, GitHub did not send me any notification on new issues to my mail. One colleague of mine actually told me about open issues. :(

I will look into it, but don't know how complicated it is.

**Comment by j-frei** [comment]
Should be working now. :)
Unfortunately, changing the resolution is too complex without messing with a lot of constants in the binary.
However, the camera can be moved easily now.

**Comment by Linkinsoldier** [comment]
Thanks for the Update. Github did not notify me about the response either ;)

I just used it and it seems to work great - thank you very much!

**Comment by j-frei** [comment]
Hey, thanks for pointing me to the project. I've never heart of it so far, but this looks nice.
