### ISSUE TITLE
Support for a no-cd edition of Empire Earth.exe

### ISSUE THREAD

**Issue by n-ice-ch** [j-frei/EmpireEarthZoomChanger#5]
I do play EE since the release in 2001.
One of the first thing we did was to exchange the original binary with a no-cd one.
Combined with a patch to allow 5000 population, I and my friends are very happy to play the game in 2022 too.

I do request for support for your zoom changer for this special EXE (attached).

Thank you.
[Empire Earth.zip](https://github.com/j-frei/EmpireEarthZoomChanger/files/10323611/Empire.Earth.zip)

**Comment by j-frei** [comment]
Hey, @n-ice-ch 

Thank you for providing the file! It should be included now, but I'd like you to verify it.
- Does the zoom patch work during gameplay?
- Does the zoom patch work in the editor?

Cheers,
Johann

**Comment by n-ice-ch** [comment]
@j-frei 
Thank you for your fast reaction. Great support!

I did a test-game and the zoom is working.

I also check the editor and it looks like the zoom is working too (because I did never use this tool, I can only estimate the advanced zoom level).

On my opinion you can close the issue with: fixed.

**Comment by j-frei** [comment]
Thanks for validating the updated version! I'll close this issue.
